# Generated by Django 6.0.3 on 2026-09-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=100)),
            ],
        ),
    ]
